name: docker build and push

on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: docker login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.azure_registry }}
          username: ${{ secrets.azure_registry_username }}
          password: ${{ secrets.azure_registry_password }}
      -
        name: docker build and push
        run: docker build -t test .
        
      - name: docker push
        run: docker push test:lastest
          
  
  
